/** Lorentz (hyperboloid) model of H^n, K=-1 — mirror of src/hypviz/kernel/lorentz.py.
 * Validated against golden vectors generated by the Python kernel (source of truth). */
export type Vec = number[];

const EPS = 1e-15;

export const add = (a: Vec, b: Vec): Vec => a.map((ai, i) => ai + b[i]);
export const scale = (c: number, a: Vec): Vec => a.map((ai) => c * ai);

/** Minkowski inner product <x,y>_L. */
export const mdot = (x: Vec, y: Vec): number =>
  x.reduce((s, xi, i) => s + xi * y[i], 0) - 2 * x[0] * y[0];

export const origin = (n: number): Vec => [1, ...Array(n).fill(0)];

/** Lift spatial coordinates onto the hyperboloid: x0 = sqrt(1+|xs|^2). */
export const fromSpatial = (xs: Vec): Vec =>
  [Math.sqrt(1 + xs.reduce((s, v) => s + v * v, 0)), ...xs];

/** Project an ambient vector u onto the tangent space at x. */
export const toTangent = (x: Vec, u: Vec): Vec => add(u, scale(mdot(x, u), x));

/** Geodesic distance d(x,y) = arccosh(-<x,y>_L). */
export const dist = (x: Vec, y: Vec): number => Math.acosh(Math.max(-mdot(x, y), 1));

/** exp_x(v) = cosh(|v|) x + sinh(|v|)/|v| v, for v in T_x. */
export const expmap = (x: Vec, v: Vec): Vec => {
  const t = Math.sqrt(Math.max(mdot(v, v), 0));
  return add(scale(Math.cosh(t), x), scale(Math.sinh(t) / Math.max(t, EPS), v));
};

/** Inverse of expmap: the tangent vector at x pointing to y. */
export const logmap = (x: Vec, y: Vec): Vec => {
  const a = Math.max(-mdot(x, y), 1);
  const c = Math.acosh(a) / Math.max(Math.sqrt(a * a - 1), EPS);
  return y.map((yi, i) => c * (yi - a * x[i]));
};

/** Parallel transport of v in T_x along the geodesic to T_y. */
export const ptransp = (x: Vec, y: Vec, v: Vec): Vec => {
  const c = mdot(y, v) / (1 - mdot(x, y));
  return v.map((vi, i) => vi + c * (x[i] + y[i]));
};

/** gamma(t) on the geodesic with gamma(0)=x, gamma(1)=y. */
export const geodesic = (x: Vec, y: Vec, t: number): Vec => expmap(x, scale(t, logmap(x, y)));
