/** Lorentz (hyperboloid) model of H^n, curvature K < 0 — mirror of
 * src/hypviz/kernel/lorentz.py. Validated against golden vectors generated by
 * the Python kernel (source of truth). */
export type Vec = number[];

const EPS = 1e-15;
const R = (k: number) => 1 / Math.sqrt(-k);

export const add = (a: Vec, b: Vec): Vec => a.map((ai, i) => ai + b[i]);
export const scale = (c: number, a: Vec): Vec => a.map((ai) => c * ai);

/** Minkowski inner product <x,y>_L. */
export const mdot = (x: Vec, y: Vec): number =>
  x.reduce((s, xi, i) => s + xi * y[i], 0) - 2 * x[0] * y[0];

export const origin = (n: number, k = -1): Vec => [R(k), ...Array(n).fill(0)];

/** Lift spatial coordinates onto the hyperboloid: x0 = sqrt(R^2+|xs|^2). */
export const fromSpatial = (xs: Vec, k = -1): Vec =>
  [Math.sqrt(R(k) ** 2 + xs.reduce((s, v) => s + v * v, 0)), ...xs];

/** Project an ambient vector u onto the tangent space at x. */
export const toTangent = (x: Vec, u: Vec, k = -1): Vec => add(u, scale(mdot(x, u) / R(k) ** 2, x));

/** Geodesic distance d(x,y) = R arccosh(-<x,y>_L / R^2). */
export const dist = (x: Vec, y: Vec, k = -1): number =>
  R(k) * Math.acosh(Math.max(-mdot(x, y) / R(k) ** 2, 1));

/** exp_x(v) = cosh(|v|/R) x + R sinh(|v|/R) v/|v|, for v in T_x. */
export const expmap = (x: Vec, v: Vec, k = -1): Vec => {
  const r = R(k), t = Math.sqrt(Math.max(mdot(v, v), 0));
  return add(scale(Math.cosh(t / r), x), scale((r * Math.sinh(t / r)) / Math.max(t, EPS), v));
};

/** Inverse of expmap; the R factors cancel except inside a. */
export const logmap = (x: Vec, y: Vec, k = -1): Vec => {
  const a = Math.max(-mdot(x, y) / R(k) ** 2, 1);
  const c = Math.acosh(a) / Math.max(Math.sqrt(a * a - 1), EPS);
  return y.map((yi, i) => c * (yi - a * x[i]));
};

/** Parallel transport of v in T_x along the geodesic to T_y. */
export const ptransp = (x: Vec, y: Vec, v: Vec, k = -1): Vec => {
  const c = mdot(y, v) / (R(k) ** 2 - mdot(x, y));
  return v.map((vi, i) => vi + c * (x[i] + y[i]));
};

/** gamma(t) on the geodesic with gamma(0)=x, gamma(1)=y. */
export const geodesic = (x: Vec, y: Vec, t: number, k = -1): Vec =>
  expmap(x, scale(t, logmap(x, y, k)), k);
